export const COURSE_URL = 'https://pay.kiwify.com.br/GAQHdpq';
export const YOUTUBE_CHANNEL = 'https://www.youtube.com/@NerdKing';
export const PORTFOLIO_COUPON = 'VIMDOPORTIFOLIO';
export const PORTFOLIO_COUPON_DISCOUNT = 30;

/** @typedef {{ id: string; youtubeId: string; titlePt: string; titleEn: string; durationHint: string; modulePt: string; moduleEn: string }} Lesson */

/** @type {Lesson[]} */
export const lessons = [
  {
    id: '01',
    youtubeId: 'wWwxnl0bnrA',
    titlePt: 'Configure seu ambiente profissional (VS Code + IA)',
    titleEn: 'Set up a professional environment (VS Code + AI)',
    durationHint: 'Ambiente',
    modulePt: 'Fundamentos',
    moduleEn: 'Fundamentals',
  },
  {
    id: '02',
    youtubeId: 'YDwNuEct5mE',
    titlePt: 'O que é HTML? A base de toda página da internet',
    titleEn: 'What is HTML? The base of every web page',
    durationHint: 'HTML',
    modulePt: 'Fundamentos',
    moduleEn: 'Fundamentals',
  },
  {
    id: '03',
    youtubeId: 'giu5uiaFDkA',
    titlePt: 'Por que seu HTML está feio? Descobrindo o CSS',
    titleEn: 'Why does your HTML look plain? Discovering CSS',
    durationHint: 'CSS',
    modulePt: 'Fundamentos',
    moduleEn: 'Fundamentals',
  },
  {
    id: '04',
    youtubeId: 'kfeRzs0n6ow',
    titlePt: 'Criando sua primeira página HTML do zero',
    titleEn: 'Building your first HTML page from scratch',
    durationHint: 'Prática',
    modulePt: 'Fundamentos',
    moduleEn: 'Fundamentals',
  },
  {
    id: '05',
    youtubeId: 'wErLdWDeaog',
    titlePt: 'Desafios técnicos para vagas de desenvolvedor',
    titleEn: 'Technical challenges for developer roles',
    durationHint: 'Carreira',
    modulePt: 'Mentalidade',
    moduleEn: 'Mindset',
  },
  {
    id: '06',
    youtubeId: 'zLbVIML47YM',
    titlePt: 'Preparando o projeto: download dos assets',
    titleEn: 'Project setup: downloading the assets',
    durationHint: 'Projeto',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '07',
    youtubeId: 'p2ZjINmoajM',
    titlePt: 'Criando o header profissional',
    titleEn: 'Building a professional header',
    durationHint: 'Header',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '08',
    youtubeId: 'Bx1N6VNkD0c',
    titlePt: 'Estilizando o header com CSS',
    titleEn: 'Styling the header with CSS',
    durationHint: 'CSS',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '09',
    youtubeId: 'sg2KNWZFujQ',
    titlePt: 'Criando o hero banner',
    titleEn: 'Building the hero banner',
    durationHint: 'Hero',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '10',
    youtubeId: 'bdrMTzgwc0A',
    titlePt: 'Estilizando o hero banner',
    titleEn: 'Styling the hero banner',
    durationHint: 'CSS',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '11',
    youtubeId: 'moHOjG16TSQ',
    titlePt: 'Google Fonts: tipografia profissional',
    titleEn: 'Google Fonts: professional typography',
    durationHint: 'Tipografia',
    modulePt: 'Projeto real',
    moduleEn: 'Real project',
  },
  {
    id: '12',
    youtubeId: 'jTretXpBXQk',
    titlePt: '3 desafios JavaScript que separam júnior de pleno',
    titleEn: '3 JavaScript challenges that separate junior from mid-level',
    durationHint: 'JS',
    modulePt: 'JavaScript',
    moduleEn: 'JavaScript',
  },
  {
    id: '13',
    youtubeId: 'P5ORu8Sofu8',
    titlePt: 'O desafio JavaScript que iniciantes erram',
    titleEn: 'The JavaScript challenge beginners miss',
    durationHint: 'JS',
    modulePt: 'JavaScript',
    moduleEn: 'JavaScript',
  },
  {
    id: '14',
    youtubeId: 'C0xy3JvvkV8',
    titlePt: 'Números primos em JavaScript',
    titleEn: 'Prime numbers in JavaScript',
    durationHint: 'Algoritmo',
    modulePt: 'JavaScript',
    moduleEn: 'JavaScript',
  },
  {
    id: '15',
    youtubeId: '0hb8IKb2iow',
    titlePt: 'Somar apenas os pares em JavaScript',
    titleEn: 'Sum only even numbers in JavaScript',
    durationHint: 'Algoritmo',
    modulePt: 'JavaScript',
    moduleEn: 'JavaScript',
  },
];
